### ISSUE TITLE
Hint: milestones

### ISSUE THREAD

**Issue by alexandre-mbm** [TheFive/osmbc#80]
At least some issues. Suggestion:

- [ ] One milestone for next release
- [ ] Milestone**s** by features
  - [ ] One milestone for languages support (from issue #45)

**Comment by TheFive** [comment]
I thougth about it, but did not realize it yet. It can help to make more transparency.

**Comment by alexandre-mbm** [comment]
When the mount of issues grow it will become more difficult to organize them.
